#pragma once
#include "NativeGameplayTags.h"

namespace KausGameplayTags
{
	//Message - UI
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Kaus_Event_UI_Toggle);

	//UI
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Game);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_GameOnMenu);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Menu);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Modal);

	//UI - HUD - Panel 
	/* todo: make more simple and concise */
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_HUD_MainCanvas);

	//Input - Native
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);

	//Game Phase
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Phase_None);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Phase_Loading);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Phase_Title);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Phase_Exploration);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Phase_Battle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Phase_Battle_PlayerTurn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Phase_Battle_EnemyTurn);

	//Event - Phase Changed
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Kaus_Event_Phase_Changed);

	//Movement
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_MovementStopped);

	//Interaction
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_INTERACTION_DURATION_MESSAGE);


	//Hardware
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Platform_Trait_Input_HardwareCursor);

	//Ability System - Message
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_SIMPLE_FAILURE_MESSAGE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_PLAY_MONTAGE_FAILURE_MESSAGE);

	//Unit status state
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Unit_Status_Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Unit_Status_Death_Dying);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Unit_Status_Death_Dead);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
}
